/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.blogspot.mstachniuk.android.db4o;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int afterLogin=0x7f040000;
        public static final int afterLoginLabel=0x7f040001;
        public static final int createUserMenu=0x7f040002;
        public static final int loginMenu=0x7f040003;
        public static final int mainMenu=0x7f040004;
    }
    public static final class idCreateUserMenu {
        public static final int createButton=0x7f050004;
        public static final int loginEntry=0x7f050001;
        public static final int loginLabel=0x7f050000;
        public static final int passwordEntry=0x7f050003;
        public static final int passwordLabel=0x7f050002;
    }
    public static final class idLogin {
        public static final int loginButton=0x7f060004;
        public static final int loginEntry=0x7f060001;
        public static final int loginLabel=0x7f060000;
        public static final int passwordEntry=0x7f060003;
        public static final int passwordLabel=0x7f060002;
    }
    public static final class idMainMenu {
        public static final int createNewUser=0x7f070000;
        public static final int loginButton=0x7f070001;
    }
    public static final class layout {
        public static final int afterlogin=0x7f020000;
        public static final int createuser=0x7f020001;
        public static final int login=0x7f020002;
        public static final int main=0x7f020003;
    }
    public static final class string {
        public static final int app_name=0x7f030000;
    }
}
